#!/bin/bash

##############################################
## Deutsch Armee Messer / Der Armee Mann    ##
## My personal take on the Swiss Army Knife ##
##############################################
## Current functions include:		        ##
##	- Wordpress (Partial)		            ##
##	- Joomla (Partial)		                ##
##############################################
## Future functions include:		        ##
##	- Iptables			                    ##
##	- Check Root Kits		                ##
##	- Check Malicious Files		            ##
## Stay tuned for more!	Email:admin@krux.us ##
##############################################

package="Deutsch Armee Messer";
opt=${1};
arg1=${2};
arg2=${3};

####################
## Conf Functions ##
####################

function wp_conf {
wp=(
        $(grep -i DB_U wp-config.php | awk -F"'" '{print $4}')
        $(grep -i DB_P wp-config.php | awk -F"'" '{print $4}')
        $(grep -i DB_N wp-config.php | awk -F"'" '{print $4}')
        $(grep -i table_prefix wp-config.php | awk -F"'" '{print $2}'));

}

function jos_conf {
joom=(
        $(grep -i db configuration.php | awk -F"'" ' NR==2 {print $2}')
        $(grep -i user configuration.php | awk -F"'" ' NR==1 {print $2}')
        $(grep -i password configuration.php | awk -F"'" '{print $2}')
        $(grep -i live_site configuration.php | awk -F"'" '{print $2}')
        $(grep -i dbprefix configuration.php | awk -F"'" '{print $2}'));
}

####################
## Help Functions ##
####################

function hilfe {
echo -e "$package - A multi-tool for administrators\n
dam-cli [options] [arguments]\n
options:\n
\th, -h, --help                show brief help\n
\twp, -wp, --wordpress       executes Wordpress functions\n
\tjos, -jos, --joomla      executes joomla functions\n
\tip, -ip, --iptables	executes iptables functions\n
\tchkrk, -chkrk, --chkrk	checks for known rootkits\n
\tchkmf, -chkmf, --chkmf	checks for known malicious files/code\n"
exit 0
}

function wp_hilfe {
echo -e "dam-cli wp [options]\n
options:\n
\th, -h, --help\n\tshow brief help\n
\tplugins, -plugins, --plugins\n\tshows plugins active, activates wp_plugins function with more options\n
\t\tenable, -enable, --enable [options]\n\t\tenables specified plugin(s)\n
\t\tdisable, -disable, --disable [options]\n\t\tdisables specified plugin(s) or all\n
\t\treenable, -reenable, --reenable\n\t\tre-enables most recently disabled plugins\n
\ttheme, -theme, --theme\n\tshows current theme, activates wp_themes function with more options\n
\t\tset, -set, --set [options]\n\t\tsets the specified theme (must be installed)\n
\t\treset, -reset, --reset\n\t\tattempts to reset the theme, theme must be in WP repo\n
\tpass, -pass, --pass\n\tresets the current Wordpress password\n
\tcore, -core, --core\n\treplaces the core files for Wordpress
\t(note: clears the themes and plugins folders)\n"
exit 0
}

function jos_hilfe {
echo -e "dam-cli jos [options]\n
options:\n
\th, -h, --help\n\tshow brief help\n
\tinfo, -info, --info\n\tshows the config info for Joomla\n
\tpass, -pass, --pass\n\tresets the current Joomla password\n"
exit 0
}


function ip_hilfe {
echo -e "dam-cli ip [options]\n
options:\n
\tadd, -add, --add		adds a rule to iptables\n
\tkill, -kill, --kill		kills a rule to iptables\n
\tp, port, -p, -port, --port	opens a port in iptables\n"
exit 0
}

function wp_plugins_hilfe { echo -e "Wordpress Plugins Help -- Under Construction"; break; }

#########################################################
## Secondary Functions (wp_plugins, jos_plugins, etc.) ##
#########################################################

## Wordpress specific

function wp_plugins { 
        case "${arg2}" in
                h|-h|--help)
                        echo "Under Construction"; break;
                        ;;
                disable|-disable|--disable)
                        echo -e "\e[1m[\e[32m+\e[0m\e[1m]\e[0mDisabling Plugins..."
			wp_plugins_disable
                        ;;
                reenable|-reenable|--reenable)
	                echo -e "\e[1m[\e[32m+\e[0m\e[1m]\e[0mRe-enabling Plugins..."
			wp_plugins_reenable        
			;;
		enable|-enable|--enable)
			echo "Under Construction - Enable"; break;
        esac

}

function wp_plugins_disable {
	wp_conf
	mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; SELECT * FROM wp_options WHERE option_name = 'active_plugins';" | awk -F"|" '{print $1}' | awk 'NR==2 {print $3}' > /tmp/dam-cli_plugins_backup_$(echo ${PWD}|awk -F/ '{print $3}');
	mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; UPDATE wp_options SET option_value = '' WHERE option_name = 'active_plugins';" && echo -e "\e[1m[\e[32m+\e[0m\e[1m]\e[0mPlugins Disabled"
exit 0
}

function wp_plugins_reenable {
	#To re-enable plugins
	wp_conf
	mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; UPDATE wp_options SET option_value = '$(cat /tmp/dam-cli_plugins_backup_$(echo ${PWD}|awk -F/ '{print $3}'))' WHERE option_name = 'active_plugins';" && echo  -e "\e[1m[\e[32m+\e[0m\e[1m]\e[0mPlugins Re-enabled"
	exit 0
}

function wp_themes { echo -e "Wordpress Themes -- Under Construction"; break;}

function wp_info {
	wp_conf
	mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; SELECT * FROM wp_options WHERE option_id IN ('3','1','2','41','42');"
echo -e '\n\e[1;32mWordpress Info:\n\e[0m';
echo -e "Database Name: ${wp[2]}
Database User: ${wp[0]}
Database Password: ${wp[1]}
Database Prefix: ${wp[3]}\n"
echo -e '\e[1;32mEnabled Plugins:\e[0m';
echo
mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; SELECT * FROM wp_options WHERE option_name = 'active_plugins';" | grep -Po '".*?"' | sed 's/"//g'
echo
exit 0	
}

function wp_pass { 
	wp_conf
	newpass="$(date +%s | sha256sum | base64 | head -c 16 ; echo)"
	user=$(mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; 
		SELECT ID, user_login FROM wp_users WHERE ID=1 LIMIT 1" | 
		awk -F"|" 'NR==2 {print $1}' | awk '{print $2}')
	pass=$(mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]}; 
		SELECT ID, user_login FROM wp_users WHERE ID=1 LIMIT 1; 
		UPDATE wp_users SET user_pass = MD5('${newpass}')")
	url=$(mysql -u ${wp[0]} -p${wp[1]} -e "USE ${wp[2]};
		SELECT * FROM wp_options WHERE option_name = 'siteurl'" |
		awk -F"|" 'NR==2 {print $1}' | awk '{print $3}')

	echo -e "\e[1;32m[*]Wordpress Password Reset:\e[0m\nURL: ${url}/"wp-admin"\nUsername: ${user}\nPassword: ${newpass}"
	exit 0
}

function wp_core {
	echo -e "This is a placeholder for the Wordpress core file replacement function. Check back later brah."; break;
}

## Joomla-specific

function jos_info {
jos_conf
echo -e '\n\e[1;32mJoomla Info:\n\e[0m'; 
echo -e "Live Site: ${joom[3]}
Database Name: ${joom[0]}
Database User: ${joom[1]}
Database Password: ${joom[2]}
Database Prefix: ${joom[4]}\n"; 
echo -e '\e[1;32mTesting Database Connection....\n\e[0m'; 
mysql -u ${joom[1]} -p${joom[2]} -e "USE ${joom[0]}" && 
	if true 
		then echo -e "Connection Successful, looks good.\n"; 
	else 
		die "Connection is muerte"; 
	fi
exit 0
}
function jos_pass { echo -e "Joomla Password -- Under Constructions"; break;}

##########################################################
## Primary Functions (wordpress, joomla, iptable, etc.) ##
##########################################################

function joomla { 
	case "${arg1}" in
		h|-h|--help)
			echo -e "[*]Displays this help box"
			jos_hilfe
			;;
		info|-info|--info)
			jos_info
			;;
		pass|-pass|--pass)
			jos_pass
			;;
		*)
			jos_hilfe
			;;
	esac
}

function wordpress { 
	case "${arg1}" in
		h|-h|--help)
			echo -e "[*]Displays this help box"
			wp_hilfe
			;;
		info|-info|--info)
			wp_info
			;;
		plugins|-plugins|--plugins)
			wp_plugins
			;;
		core|-core|--core)
			wp_core
			;;
		themes|-themes|--themes)
			wp_themes
			;;
		pass|-pass|--pass)
			wp_pass
			;;
		*)
			wp_hilfe
			;;
	esac	
}

function ip { echo -e "[${opt}] [${arg1}]"; break;}
function chkrk { echo -e "[${opt}] [${arg1}]"; break;}
function chkmf { echo -e "[${opt}] [${arg1}]"; break;}

#########################
## Main Case Statement ##
#########################

if [ $# -eq 0 ] 
	then
		echo -e "[*]No parameters applied"  
		hilfe
	else 
		while test $# -gt 0; do
        		case "${1}" in
                		h|-h|--help)
					hilfe
                        		;;
                		wp|-wp|--wordpress)
					wordpress
					;;
                		jos|-jos|--joomla)
					joomla
					;;
				ip|-ip|--iptables)
					ip
					;;
				chkrk|-chkrk|--chkrk)
					chkrk
					;;
				chkmf|-chkmf|--chkmf)
					chkmf
					;;
				*)
					echo "[*]Invalid parameter applied"
					hilfe			
                        		;;
        		esac
		done
fi
